### ISSUE TITLE
Get involved content

### ISSUE THREAD

**Issue by proemmer** [insite-gmbh/iDoc#3]
Add content that describes how and external user help us to improve the documentation.

- [x] Create pull request (so the user can edit the pages by themselve by using the Improve this Document button)- He has to be a registred Github user

- [x] Give feedback or suggestions by using the Issues  (we have to create a lable for each software and also some other lables like Question, Suggestion, ....)

**Comment by insite-Jan** [comment]
I guess this can be closed aswell?
